name: Branch-Preview Action
description: Preview your latest branch changes on a sub domain
branding:
  icon: 'upload-cloud'
  color: 'red'
inputs:
  host:
    description: 'This is your dokku host address to push the branch to'
    required: true
  port:
    description: 'If your ssh port into the dokku host is not default 22, set it here.'
    required: false
    default: '22'
  dokku_key:
    description: 'This is the ssh/dokku private key that allows pushing to the dokku'
    required: true
  domain:
    description: 'This is the domain to map to'
    required: true
  github_token:
    description: 'Github access token'
    required: true
  github_primary_branch:
    description: 'Name of your primary branch, some use master, new default is main'
    required: false
    default: 'main'

runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        DOKKU_KEY: ${{ inputs.dokku_key }}
        HOST: ${{ inputs.host }}
        PORT: ${{ inputs.port }}
        DOMAIN: ${{ inputs.domain }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_PRIMARY_BRANCH: ${{ inputs.github_primary_branch}}
        
